"""add pgvector support

Revision ID: b2fb1e06dce7
Revises: 
Create Date: 2026-05-26 21:19:31.665758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'b2fb1e06dce7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Enable pgvector extension safely
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    
    # Create embeddings table
    op.create_table('style_guide_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archetype', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=768), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('style_guide_embeddings')
    # ### end Alembic commands ###
